### PR TITLE
Route for custom back-halves

### PR DESCRIPTION
**Pull request by Sundroid-ops**
Set up backend logic for custom back-halve which generates both back-halve URL and short URL.

### CODE REVIEW

**Comment by DhananjayThomble** [comment]
> Set up backend logic for custom back-halve which generates both back-halve URL and short URL.

pls try to generate short URL for this:
```
{
    "url": "https://github.com/DhananjayThomble/URL-Shortener-App/pull/89/files"
}
```

I'm getting this response:
```
{
    "shortUrl": "https://dturl.live/u/xyzMau_2lO",
    "customUrl": "http://localhost:4001/com.com/u/game"
}
```
here 'shortUrl' is perfect but 'customUrl' doesn't look good to me (com.com)

**Comment by DhananjayThomble** [comment]
Also we need to make sure that The custom back-halve should be unique for the entire system so that any user can create and use a short URL for any URL, regardless of the user who created the short URL.

**Comment by Sundroid-ops** [comment]
@DhananjayThomble let me fix this.

**Comment by Sundroid-ops** [comment]
@DhananjayThomble Can you see if you want any changes for my plan for assigning custom-back-halves:

1. Preventing user from using same back-halve for the same domain if they have already registered that but allowing the same user to use it for different domains.
     For ex:   youtube.com/example and github.com/example
2. Unique back-halve for everyone.

Let me know if this needs any change.

**Comment by DhananjayThomble** [comment]
> @DhananjayThomble Can you see if you want any changes for my plan for assigning custom-back-halves:
> 
> 1. Preventing user from using same back-halve for the same domain if they have already registered that but allowing the same user to use it for different domains.
>    For ex:   youtube.com/user_1 and github.com/user_1
> 2. Unique back-halve for everyone.
> 
> Let me know if this needs any change.

Currently, our system primarily focuses on a single domain, which is 'dturl.live.' In this context, the standard URL shortening process generates a short URL like 'https://dturl.live/u/_9znCj5h6r' for an original link like 'https://www.freecodecamp.org/news/project-based-learning/'

Desired Flow:

Request Body:
You provide a custom back-halve, let's say 'dev-tips' Along with it, you specify the original URL.

Expected Response: In return, you receive a short URL: 'https://dturl.live/u/dev-tips'

Feel free to reach out to me if you have any doubts or need assistance

**Pull request merged**
