### PR TITLE
Creating root Package.json Configuration

### LINKED ISSUE #172: Set Up a package.json Script to Run Frontend and Backend from the Main Folder
- [ ] Creating a package.json file in the root folder

for easy Installation create scripts: 

- [ ] Install-frontend

- [ ] Install-backend

- [ ] Install

easy starting of application, creating scripts: 

- [ ] Frontend
- [ ] Backend
- [ ] start
- [ ] build-frontend. 

this will improve the developer experience and increase readability and understand-ability of code

@DhananjayThomble, Please review this issue and if this is required, would like to work on this issue, please assign this to me and add **hacktoberfest** label to it

### PR DESCRIPTION
**Pull request by keshav-nischal**
Fixes #172

### CODE REVIEW

**Comment by keshav-nischal** [comment]
@DhananjayThomble, please review the pull request and tell me if it can improved

**Comment by DhananjayThomble** [comment]
Hello @keshav-nischal, which OS are you using?

**Comment by keshav-nischal** [comment]
@DhananjayThomble linux ubuntu

**Comment by DhananjayThomble** [comment]
> @DhananjayThomble linux ubuntu

Fine, actually I'm having trouble with some scripts on my Windows 11 system. I suggest trying to use` "install-frontend": "cd frontend && npm install"` to see if it works on your system as well. If it does, we can proceed with this option.

Alternatively, using the `"cd directory && command"` method first changes the current working directory to the specified directory, then runs the command. However, the` --prefix` option runs the npm command in a different directory without changing the current working directory. I guess this might be causing issues in a windows environment just like mine.

**Comment by DhananjayThomble** [comment]
@keshav-nischal, you can connect with me on Discord [@dhananjay_thomble](https://discord.com/users/dhananjay_thomble) or on LinkedIn.

**Pull request closed without merging**
