### PR TITLE
change faicon icon

### PR DESCRIPTION
**Pull request by rihamnazeer**

### CODE REVIEW

**Comment by DhananjayThomble** [comment]
> _ No description provided. _

Hello @rihamnazeer, could you please provide 'logo.png' as well? It would be helpful for the web app splash screen.

**Comment by rihamnazeer** [comment]
✔️ 👍

**Comment by rihamnazeer** [comment]
change it

**Comment by DhananjayThomble** [comment]
> change it

There is no file for merging, I guess you've deleted it

**Comment by rihamnazeer** [comment]
ok

**Pull request closed without merging**
